### ISSUE TITLE
Generalize Services Code

### ISSUE THREAD

**Issue by brotherdust** [johnbaiMSFT/Samples#1]
This is really great! Thanks for all the info!
If I could make a suggestion: could you maybe break out the code that handles Windows Service-specific functions into a different file? There are several reasons for this:

1. Running code as a service is really interesting.
2. Breaking it out into it's own file whatever construct you think is appropriate helps maintain context for the reader: "I'm looking at code that pertains the Windows Services. Ah! Look at that! Cool!"
3. Generalizing it means you only have to solve the problem once and can re-use it anywhere (ideally).

Anyway, just some humble suggestions from a fellow non-professional developer. =)

**Comment by johnbaiMSFT** [comment]
Sorry for the late reply. This has been resolved, I believe. If not, feel free to let me know. :)
